name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      with:
        os: ubuntu

    - name: Build release artifacts
      run: |
        make clean
        make
        mkdir -p artifacts
        cp build/libbin.so artifacts/
        cp -r src/*.h artifacts/
        tar -czf artifacts/libbin-src.tar.gz src/ test/ Makefile README.markdown

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/libbin-src.tar.gz
        asset_name: libbin-src.tar.gz
        asset_content_type: application/gzip
